# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
host: 0.0.0.0
title: Nottario
stripe_key: pk_live_Yh6sSgUn7kMzAGWiPu9YuN9X
stripe_price: 9999
stripe_currency: gbp
stripe_visible_price: £99.99
stripe_name: Exor Ventures Ltd (Nottario)
payment_lambda: https://u0w7zfpnti.execute-api.eu-west-1.amazonaws.com/prod/nottarioFiatPayment
get_lambda: https://u0w7zfpnti.execute-api.eu-west-1.amazonaws.com/prod/nottarioFiatGet
check_lambda: https://u0w7zfpnti.execute-api.eu-west-1.amazonaws.com/prod/nottarioFiatCheck
contact_lambda: https://u0w7zfpnti.execute-api.eu-west-1.amazonaws.com/prod/nottarioFiatContact
email: your-email@example.com
twitter: "@nottar_io"
success_url: success.html
error_url: error.html
upload_url: https://u0w7zfpnti.execute-api.eu-west-1.amazonaws.com/prod/nottarioFiats3Upload
ipfs_check: https://u0w7zfpnti.execute-api.eu-west-1.amazonaws.com/prod/nottarioFiatipfsCheck
recaptcha_key: 6LeU9VAUAAAAAA0_ucqoFquRQ2LUpa9lVX46oCmV
GA_TRACKING_ID: UA-48512013-2
